/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HASShelterEmployeeRole;

import userInterface.HASEmployeeRole.*;
import business.EcoSystem;
import business.Organization;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organisation.HasHealthcareRepresentativeOrganisation;
import business.organisation.HasShelterOrganisation;
import business.organisation.ReceptionistOrganisation;
import business.roles.AdminRole;
import business.roles.Role;
import business.userAccount.UserAccount;
import business.workQueue.PatientTestRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import static java.awt.image.ImageObserver.PROPERTIES;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PRANJAL
 */
public class HASShelterEmployeeWorkStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HAsEmployeeWorkStatusJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    HasShelterOrganisation organization;
    Enterprise enterprise;
    EcoSystem business;

    public HASShelterEmployeeWorkStatusJPanel(JPanel userProcessContainer, UserAccount account, HasShelterOrganisation organization, Enterprise enterprise, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        initComponents();
        populateTable();
        populateJComboBox();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblWorkRequestForShelter.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getListOfWorkRequests()) {
                Object[] row = new Object[4];
                row[0] = request;
                        row[1] = request.getAssignedFor();
                        row[2] = request.getAssignedShelter();
                        row[3] = request.getStatus();
                model.addRow(row);
        }
    }

    public void populateJComboBox() {
        comboBoxSelectShelter.removeAllItems();
        for (Network network : business.getListOfNetworks()) {
            for (Enterprise enter : network.getEnterpriseDirectory().getListOfEnterprises()) {
                if (enter.getEnterpriseType().equals(Enterprise.EnterpriseType.NGO.getValue())) {
                    comboBoxSelectShelter.addItem(enter);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxSelectShelter = new javax.swing.JComboBox();
        btnAssignShelter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequestForShelter = new javax.swing.JTable();
        lblNewShelter = new javax.swing.JLabel();
        lblSelectShelter = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        comboBoxSelectShelter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxSelectShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSelectShelterActionPerformed(evt);
            }
        });

        btnAssignShelter.setBackground(new java.awt.Color(99, 200, 242));
        btnAssignShelter.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        btnAssignShelter.setText("ASSIGN SHELTER");
        btnAssignShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignShelterActionPerformed(evt);
            }
        });

        tblWorkRequestForShelter.setBackground(new java.awt.Color(99, 200, 242));
        tblWorkRequestForShelter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblWorkRequestForShelter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Assigned for", "Assigned Shelter", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequestForShelter);

        lblNewShelter.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        lblNewShelter.setText("REQUEST FOR NEW SHELTER");

        lblSelectShelter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectShelter.setText("Select Shelter: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(lblSelectShelter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxSelectShelter, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNewShelter))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignShelter)
                .addGap(373, 373, 373))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNewShelter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSelectShelter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectShelter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignShelter)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSelectShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSelectShelterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSelectShelterActionPerformed

    private void btnAssignShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignShelterActionPerformed
        // TODO add your handling code here:
        Enterprise ent = (Enterprise) comboBoxSelectShelter.getSelectedItem();
        int selectedRow = tblWorkRequestForShelter.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please make a selection");
            return;
        }
        WorkRequest request = (WorkRequest) tblWorkRequestForShelter.getValueAt(selectedRow, 0);
        if (request.getStatus().equals("Shelter Requested")) {
            JOptionPane.showMessageDialog(null, "Already Shelter Requested");
            return;
        }
         if (request.getStatus().equalsIgnoreCase("Old Age Home Assigned")|request.getStatus().equalsIgnoreCase("Adult Care Shelter Assigned")|request.getStatus().equalsIgnoreCase("Child Care Shelter Assigned")){
            JOptionPane.showMessageDialog(null, "Shelter is already assigned!");
            return;
        }
        if (ent.enterpriseType.equalsIgnoreCase(Enterprise.EnterpriseType.NGO.getValue())) {
            for (UserAccount userAcc : ent.getUserAccountDirectory().getListOfUserAccounts()) {
                if (userAcc.getRole() instanceof AdminRole) {
                    request.setTypeOfRequest("ShelterAssignedRequest");
                    request.setStatus("Shelter Requested");
                    request.setReceiver(userAcc);
                    request.setAssignedShelter(ent.toString());
                    //req.setPimage("Have to upload");
                    ((UserAccount) userAcc).getWorkQueue().getListOfWorkRequests().add(request);
                    JOptionPane.showMessageDialog(null, "Requested to Shelter Admin");
             }
            }
        }
         populateTable();
    }//GEN-LAST:event_btnAssignShelterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignShelter;
    private javax.swing.JComboBox comboBoxSelectShelter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNewShelter;
    private javax.swing.JLabel lblSelectShelter;
    private javax.swing.JTable tblWorkRequestForShelter;
    // End of variables declaration//GEN-END:variables
}
