/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.registration;
import java.io.IOException;
import business.EcoSystem;
import business.roles.AdminRole;
import business.userAccount.UserAccount;
import java.awt.Graphics2D;

import business.workQueue.ShelterRequest;
import javax.swing.JFileChooser;
import java.awt.image.RenderedImage;
import javax.swing.JOptionPane;
//import java.lang.System.Logger.Level;
import business.workQueue.PatientTestRequest;

import business.enterprise.Enterprise;
import static java.awt.image.ImageObserver.PROPERTIES;
//import java.lang.System.Logger;
import javax.imageio.ImageIO;

import business.network.Network;
import java.net.URL;
import javax.swing.JPanel;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.util.Optional;
import java.io.File;

import java.net.MalformedURLException;
import userinterface.PersonalDetailsJPanel;
/**
 *
 * @author jacksonalexander
 */
public class RegistrationNeedyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationJPanel
     */
    private Network network;
    private Enterprise enterprise;
        private EcoSystem ecoSystem;
    private JPanel userProContainer;

    private final JFileChooser fileChooser = new JFileChooser();
//    ImageIcon logoImage;
    RenderedImage needyPicture;
    
    public RegistrationNeedyJPanel(JPanel userProContainer, EcoSystem ecoSystem) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProContainer = userProContainer;
        populateComboBox(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDetailsOfPersonHelping = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblRequest = new javax.swing.JLabel();
        txtRequest = new javax.swing.JComboBox<>();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jPanelPersonalDetails = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        lblHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblFT = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblLBS = new javax.swing.JLabel();
        jdcDOB = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 251, 251));

        jPanelDetailsOfPersonHelping.setBackground(new java.awt.Color(254, 254, 254));
        jPanelDetailsOfPersonHelping.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Details of Person Helping", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 24), new java.awt.Color(95, 139, 162))); // NOI18N

        lblEmail.setBackground(new java.awt.Color(254, 254, 254));
        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblEmail.setText("Email:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblContactNo.setBackground(new java.awt.Color(254, 254, 254));
        lblContactNo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblContactNo.setText("Contact No:");

        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });

        lblName.setBackground(new java.awt.Color(254, 254, 254));
        lblName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblName.setText("Name:");

        lblRequest.setBackground(new java.awt.Color(254, 254, 254));
        lblRequest.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblRequest.setText("Request for:");

        txtRequest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Health Care", "Shelter", "Both Health care and Shelter" }));

        lblLocation.setBackground(new java.awt.Color(254, 254, 254));
        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLocation.setText("Location:");

        javax.swing.GroupLayout jPanelDetailsOfPersonHelpingLayout = new javax.swing.GroupLayout(jPanelDetailsOfPersonHelping);
        jPanelDetailsOfPersonHelping.setLayout(jPanelDetailsOfPersonHelpingLayout);
        jPanelDetailsOfPersonHelpingLayout.setHorizontalGroup(
            jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                                .addComponent(lblLocation)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblRequest)))
                .addGap(42, 42, 42)
                .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                        .addComponent(lblContactNo)
                        .addGap(18, 18, 18)
                        .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelDetailsOfPersonHelpingLayout.setVerticalGroup(
            jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetailsOfPersonHelpingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblName))
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContactNo)
                        .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocation)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetailsOfPersonHelpingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequest))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnSubmit.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(72, 74, 95));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanelPersonalDetails.setBackground(new java.awt.Color(254, 254, 254));
        jPanelPersonalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Personal Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 24), new java.awt.Color(95, 139, 162))); // NOI18N

        lblFirstName.setBackground(new java.awt.Color(254, 254, 254));
        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblFirstName.setText("First Name:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblLastName.setBackground(new java.awt.Color(254, 254, 254));
        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLastName.setText("Last Name:");

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblDOB.setBackground(new java.awt.Color(254, 254, 254));
        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblDOB.setText("Date of Birth:");

        lblAge.setBackground(new java.awt.Color(254, 254, 254));
        lblAge.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblAge.setText("Age:");

        txtAge.setEnabled(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblGender.setBackground(new java.awt.Color(254, 254, 254));
        lblGender.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblGender.setText("Gender: ");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Declined To Answer" }));
        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });

        lblHeight.setBackground(new java.awt.Color(254, 254, 254));
        lblHeight.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblHeight.setText("Height:");

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        lblFT.setBackground(new java.awt.Color(254, 254, 254));
        lblFT.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblFT.setText("ft");

        lblWeight.setBackground(new java.awt.Color(254, 254, 254));
        lblWeight.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblWeight.setText("Weight:");

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        lblLBS.setBackground(new java.awt.Color(254, 254, 254));
        lblLBS.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLBS.setText("lbs");

        javax.swing.GroupLayout jPanelPersonalDetailsLayout = new javax.swing.GroupLayout(jPanelPersonalDetails);
        jPanelPersonalDetails.setLayout(jPanelPersonalDetailsLayout);
        jPanelPersonalDetailsLayout.setHorizontalGroup(
            jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblFirstName))
                            .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblGender)
                                .addComponent(lblDOB)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                                        .addComponent(lblLastName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                                        .addComponent(lblAge)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129))))
                            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblHeight)
                                .addGap(18, 18, 18)
                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFT))))
                    .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLBS)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelPersonalDetailsLayout.setVerticalGroup(
            jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDOB)
                        .addComponent(lblAge)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeight)
                    .addComponent(lblFT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeight)
                    .addComponent(lblLBS))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Profile Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 24), new java.awt.Color(95, 139, 162))); // NOI18N

        lblImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAttach.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAttach.setForeground(new java.awt.Color(75, 88, 121));
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAttach)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelDetailsOfPersonHelping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(293, 293, 293)
                            .addComponent(btnSubmit))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanelPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelDetailsOfPersonHelping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateComboBox() {
        txtLocation.removeAllItems();

        for (int i=0;i< ecoSystem.getListOfNetworks().size();i++) {
            txtLocation.addItem(ecoSystem.getListOfNetworks().get(i));
        }
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();

        String gend = genderCombo.getSelectedItem().toString();
        String request = txtRequest.getSelectedItem().toString();
        String picture = null;
                    try {
                 if(needyPicture == null) {
                    JOptionPane.showMessageDialog(null, "All fields are not entered!");
                 }
                 else {
                    ImageIO.write(needyPicture, "JPG", new File("./src/needyProfilePictures/"+firstName + lastName +"capture.jpg"));
                 }
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(PersonalDetailsJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            String file = "/needyProfilePictures/" + firstName + lastName + "capture.jpg";
            picture = file;
        if (txtFirstName.getText().isEmpty() || txtLastName.getText().isEmpty()|| txtHeight.getText().isEmpty() || txtWeight.getText().isEmpty() || txtEmail.getText().isEmpty() || txtContactNo.getText().isEmpty() || picture == null) {
            JOptionPane.showMessageDialog(null, "All fields are not entered!");
            return;
        
        } else if(!txtLastName.getText().matches("^[a-zA-Z]+$")){
            JOptionPane.showMessageDialog(null, "Only characters should be entered in Last Name","Error",JOptionPane.ERROR_MESSAGE);
             return;
             } else if(!txtEmail.getText().matches("^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$")){
            JOptionPane.showMessageDialog(null, "Email ID entered is not valid!");
            return;
        } else if(!txtName.getText().matches("^[a-zA-Z]+$")){
            JOptionPane.showMessageDialog(null, "Only characters should be entered in Contact person's Name","Error",JOptionPane.ERROR_MESSAGE);
             return;
             } else if(!txtFirstName.getText().matches("^[a-zA-Z]+$")){
            JOptionPane.showMessageDialog(null, "Only characters should be entered in First Name","Error",JOptionPane.ERROR_MESSAGE);
             return;
        
        } else if(!txtContactNo.getText().matches("^(\\+\\d{1,3}[- ]?)?\\d{10}$") && !txtContactNo.getText().matches("^\\([0-9]{3}\\)[0-9]{3}-[0-9]{4}$")){
            JOptionPane.showMessageDialog(null, "Phone No entered is not valid!");
            return;
        }
        try {
            int height = Integer.parseInt(txtHeight.getText());
            int weight = Integer.parseInt(txtWeight.getText());
             DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            DateFormat year = new SimpleDateFormat("yyyy");
            int ageDiff = 0;
            int dob = Integer.parseInt(year.format(jdcDOB.getDate()));
            ageDiff = 2021-dob;    
            txtAge.setText(String.valueOf(ageDiff));
             if ((ageDiff > 110) || (ageDiff < 1)) {
                JOptionPane.showMessageDialog(null, "Please enter a Valid birth date!");
                return;
            }
            //            pic = getPic(fname);
            Network network = (Network) txtLocation.getSelectedItem();
            //            Network currentNetwork = system.getNetworkList().get(0);
            for (int i=0; i<network.getEnterpriseDirectory().getListOfEnterprises().size();i++) {
                if (network.getEnterpriseDirectory().getListOfEnterprises().get(i).enterpriseType.equalsIgnoreCase(Enterprise.EnterpriseType.Volunteer.getValue())) {
                    for(int j=0; j<network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().size();j++) {
                        if(network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().get(j).getRole() instanceof AdminRole) {

                            if(request.equalsIgnoreCase("Health care")){
                                PatientTestRequest reques = new PatientTestRequest();
                                reques.setPatientWeight(weight);
                                reques.setPatientGender(gend);
                                reques.setPatientProfileImage(picture);
                                reques.setPatientId(PROPERTIES);
                                reques.setPatientFirstName(firstName);
                                reques.setPatientLastLame(lastName);
                                reques.setPatientHeight(height);
                                reques.setAgeOfPerson(Integer.parseInt(txtAge.getText()));
                                
                                reques.setTypeOfRequest("AssignHospital");
                                reques.setStatus("Awaiting hospital For initial checkup");
                                System.out.println("check1 "+network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().get(j).getUsername());
                                network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().get(j).getWorkQueue().getListOfWorkRequests().add(reques);
//                                for(int p=0; p<network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().get(j).getWorkQueue().getListOfWorkRequests().size(); p++) {
//                                    System.out.println("check2 "+network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().get(j).getWorkQueue().getListOfWorkRequests().get(p).getPatientFirstName());
//                                }
                                JOptionPane.showMessageDialog(this, "Patient registered succesfully. Treatment request send to HAS");
                            } else if(request.equalsIgnoreCase("Shelter")){
                                ShelterRequest r = new ShelterRequest();
                                r.setTypeOfRequest("AssignShelter");
                                r.setStatus("Awaiting for Shelter");
                                 r.setPatientLastLame(lastName);
                                r.setPatientHeight(height);
                                r.setPatientWeight(weight);
                                r.setPatientGender(gend);
                                r.setAssignedFor("Assign Shelter");
                                r.setShelterRequestName(firstName +" "+ lastName);
                                r.setObjectName(firstName +" "+ lastName);
                                r.setAgeOfPerson(Integer.parseInt(txtAge.getText()));
                                network.getEnterpriseDirectory().getListOfEnterprises().get(i).getUserAccountDirectory().getListOfUserAccounts().get(j).getWorkQueue().getListOfWorkRequests().add(r);
                                JOptionPane.showMessageDialog(this, "Person registered succesfully. Shelter request send to admin");
                            }else if(request.equalsIgnoreCase("Both Health care and Shelter")){
                                ShelterRequest r = new ShelterRequest();
                                r.setPatientId(PROPERTIES);
                                r.setPatientFirstName(firstName);
                               
                                r.setObjectName(firstName +" "+ lastName);
                                r.setTypeOfRequest("AssignShelterAndHospital");
                                r.setStatus("Shelter and Treatment Awaiting");
                                r.setAssignedFor("Assign Shelter and treatment");
                                r.setShelterRequestName(firstName +" "+ lastName);
                                r.setAgeOfPerson(Integer.parseInt(txtAge.getText()));
                                enterprise.getUserAccountDirectory().getListOfUserAccounts().get(j).getWorkQueue().getListOfWorkRequests().add(r);
                                JOptionPane.showMessageDialog(this, "Person registration is succesfull. Shelter and Treatment request is send to admin");
                            }  else {
                                JOptionPane.showMessageDialog(this, "Select form the options provided");
                                return;
                            }
                                                       
                            txtFirstName.setText("");
                            txtLastName.setText("");
                            txtHeight.setText("");
                            txtWeight.setText("");
                        }
                    }
                }
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter  Age, Height and Weight!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        JFileChooser browseDriverLicenseFile = new JFileChooser();

        //Filter image extensions
        FileNameExtensionFilter fileNameExtF = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseDriverLicenseFile.addChoosableFileFilter(fileNameExtF);
        int showOpenDial = browseDriverLicenseFile.showOpenDialog(null);
        if (showOpenDial == JFileChooser.APPROVE_OPTION) {
            File selectedImage = browseDriverLicenseFile.getSelectedFile();
            String selectedImageP = selectedImage.getAbsolutePath();

            //Display image in JLable
            ImageIcon imageI = new ImageIcon(selectedImageP);
            //Resize image to fit jlabel
            Image image = imageI.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(image));

            // construct the buffered image
            BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
            Graphics2D bImageGraphics = bufferedImage.createGraphics();
            bImageGraphics.drawImage(image, null, null);
//            RenderedImage rImage = (RenderedImage) bImage;
            needyPicture = (RenderedImage) bufferedImage;
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDetailsOfPersonHelping;
    private javax.swing.JPanel jPanelPersonalDetails;
    private com.toedter.calendar.JDateChooser jdcDOB;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFT;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLBS;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JComboBox<Object> txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtRequest;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
