/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.doctorRole;

import business.workQueue.WorkRequest;
import java.awt.Component;
import business.Organization;
import business.enterprise.Enterprise;
import business.organisation.DoctorOrganisation;
import business.organisation.NurseOrganisation;
import business.userAccount.UserAccount;
import business.EcoSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import java.awt.CardLayout;

/**
 *
 * @author PRANJAL
 */
public class DoctorBillJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorBillJPanel
     */
    JSplitPane jSplitPane;
    private JPanel userProcessContainer;
    private WorkRequest request;
    private Enterprise enterprise;
    private UserAccount userAccount;
    DoctorOrganisation doctorOrganisation;
    int count = 0;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public DoctorBillJPanel(JPanel userProcessContainer, UserAccount account, WorkRequest request, Enterprise enterprise, DoctorOrganisation doctorOrganisation, JSplitPane jSplitPane) {
        initComponents();

        this.userAccount = account;
        this.request = request;
        this.jSplitPane = jSplitPane;
        this.userProcessContainer = userProcessContainer;
        this.doctorOrganisation = doctorOrganisation;
        this.enterprise = enterprise;
        lblEnterpriseValue.setText(account.getUsername());
        populateDataInForm();
    }
    
        private void populateDataInForm() {
        txtareaSymptoms.setText(request.getPatientSymptoms());
        txtFirstName.setText(request.getPatientFirstName());
        txtAge.setText(Integer.toString(request.getAgeOfPerson()));
        txtWeight.setText(Integer.toString(request.getPatientWeight()));
        txtGender.setText(request.getPatientGender());
        txtLastName.setText(request.getPatientLastLame());
        txtBloodGroup.setText(request.getPatientBloodGroup());
        txtBloodPressure.setText(request.getPatientBloodPressure());
        txtBodyTemp.setText(Float.toString(request.getPatientBodyTemperature()));
        txtGlucoseLevel.setText(Float.toString(request.getPatientGlucoseLevel()));
        txtDiagnosis.setText(request.getPatientDiagnosis());
        txtHeight.setText(Integer.toString(request.getPatientHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaSymptoms = new javax.swing.JTextArea();
        lblLastName = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        requestTestJButton = new javax.swing.JButton();
        lblHeight = new javax.swing.JLabel();
        lblEnterpriseValue = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDiagnosis = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblGlucoseLevel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBodyTemp = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtBloodGroup = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtGlucoseLevel = new javax.swing.JTextField();
        txtBodyTemp = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        txtareaSymptoms.setEditable(false);
        txtareaSymptoms.setColumns(20);
        txtareaSymptoms.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtareaSymptoms.setRows(5);
        jScrollPane1.setViewportView(txtareaSymptoms);

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLastName.setText("Last Name");

        backJButton.setBackground(new java.awt.Color(99, 200, 242));
        backJButton.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        backJButton.setText("BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAge.setText("Age");

        requestTestJButton.setBackground(new java.awt.Color(99, 200, 242));
        requestTestJButton.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        requestTestJButton.setText("GENERATE BILL");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        lblHeight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeight.setText("Height");

        lblEnterpriseValue.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblEnterpriseValue.setText("<value>");

        lblWeight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWeight.setText("Weight");

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblEnterprise.setText("ENTERPRISE");

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGender.setText("Gender");

        lblDiagnosis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDiagnosis.setText("Possible Diagnosis");

        lblBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBloodGroup.setText("Blood Group");

        txtDiagnosis.setEditable(false);
        txtDiagnosis.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosisActionPerformed(evt);
            }
        });

        lblBloodPressure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBloodPressure.setText("Blood Pressure");

        jButton1.setBackground(new java.awt.Color(99, 200, 242));
        jButton1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton1.setText("REQUEST TREATMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblGlucoseLevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGlucoseLevel.setText("Glucose Level");

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel1.setText("DOCTOR - BILL GENERATION");

        lblBodyTemp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBodyTemp.setText("Body Temperature");

        lblSymptoms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSymptoms.setText("Symptoms");

        txtFirstName.setEditable(false);
        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLastName.setEditable(false);
        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtHeight.setEditable(false);
        txtHeight.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        txtWeight.setEditable(false);
        txtWeight.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        txtGender.setEditable(false);
        txtGender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtBloodGroup.setEditable(false);
        txtBloodGroup.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodGroupActionPerformed(evt);
            }
        });

        txtBloodPressure.setEditable(false);
        txtBloodPressure.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtGlucoseLevel.setEditable(false);
        txtGlucoseLevel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtBodyTemp.setEditable(false);
        txtBodyTemp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFirstName.setText("First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnterpriseValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(196, 196, 196))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblAge)
                            .addComponent(lblHeight)
                            .addComponent(lblWeight)
                            .addComponent(lblGender)
                            .addComponent(lblBloodGroup)
                            .addComponent(lblBloodPressure)
                            .addComponent(lblGlucoseLevel)
                            .addComponent(lblBodyTemp)
                            .addComponent(lblSymptoms)
                            .addComponent(lblDiagnosis)
                            .addComponent(backJButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtBloodGroup, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWeight, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGlucoseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(150, 150, 150))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jButton1)
                                .addGap(15, 15, 15)
                                .addComponent(requestTestJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterpriseValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAge))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHeight))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblWeight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloodGroup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloodPressure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGlucoseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGlucoseLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBodyTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSymptoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnosis))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(requestTestJButton)
                    .addComponent(jButton1))
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        if (count != 0) {
            DoctorWorkRequestStatusJPanel dwjp = new DoctorWorkRequestStatusJPanel(userProcessContainer, userAccount, doctorOrganisation, enterprise, EcoSystem.business, jSplitPane);
            jSplitPane.setRightComponent(dwjp);
        } else {
            JOptionPane.showMessageDialog(null, "Please Allocate A Process To Patient");
        }

    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        String message = JOptionPane.showInputDialog(null, "Please Enter the Bill Amount in Dollars", "Bill", JOptionPane.INFORMATION_MESSAGE);
        try{
            int flag = 0;
            String msg = "";
            if (message.isEmpty()) {
                flag = 1;
                msg = "Please Fill Appropriate Amount";
                JOptionPane.showMessageDialog(null, "Please Fill Appropriate Amount");
                return;
            }
            else {
                //request.setMessage(message);
                msg = "Bill is generated and is s ent to Receptionist";
                request.setHospitalFee(request.getHospitalFee() + Integer.parseInt(message));
                request.setSender(userAccount);
                request.setStatus("Bill Generated");
                JOptionPane.showMessageDialog(null, "Bill is generated and is s ent to Receptionist");
                count++;
            }
            JOptionPane.showMessageDialog(null, msg);
        }catch(NullPointerException e){
            //JOptionPane.showMessageDialog(null, "Bill generated and Sent to Receptionist");
            System.out.println("Cancel");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter the amount in digits");

        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void txtDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String message = JOptionPane.showInputDialog(null, "Enter Details of the Treatment", "Treatment", JOptionPane.INFORMATION_MESSAGE);
        try{
            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Enter The Appropriate Message!");
                return;
            } else {
                request.setMessage(message);
                request.setSender(userAccount);
                request.setStatus("Sent to Nurse for Treatment");
                request.setReceiver(null);
                JOptionPane.showMessageDialog(null, "Request Sent to Nurse for Treatment. Thank You!");
                count++;
                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getListOfOrganizations()) {
                    if (organization instanceof NurseOrganisation) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWorkQueue().getListOfWorkRequests().add(request);
//                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter The Appropriate Message!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblBodyTemp;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseValue;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGlucoseLevel;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtGlucoseLevel;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextArea txtareaSymptoms;
    // End of variables declaration//GEN-END:variables
}
