/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemAdminRole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.enterprise.EnterpriseDirectory;
import business.network.Network;
import business.roles.AdminRole;
import business.userAccount.UserAccount;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PRANJAL
 */
public class ManageFunds extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;

    ManageFunds(JPanel userProcessContainer, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        initComponents();
        populateNetworkTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        lblFundRequesterName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFundRequester = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        comboBoxFundRequesterName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(254, 254, 254));

        tblNetwork.setBackground(new java.awt.Color(99, 200, 242));
        tblNetwork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network  Name ", "Total Network  Funds"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNetwork);

        btnAssign.setBackground(new java.awt.Color(99, 200, 242));
        btnAssign.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblFundRequesterName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFundRequesterName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundRequesterName.setText("Funds Organization Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("All Funds Organizations in system");

        tblFundRequester.setBackground(new java.awt.Color(99, 200, 242));
        tblFundRequester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblFundRequester.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fund Requester Name ", "Status", "Message", "Fund Requested"
            }
        ));
        jScrollPane2.setViewportView(tblFundRequester);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Funds requested in system");

        comboBoxFundRequesterName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblFundRequesterName)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxFundRequesterName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFundRequesterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFundRequesterName))
                .addGap(18, 18, 18)
                .addComponent(btnAssign)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int row = tblFundRequester.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest request = (WorkRequest) tblFundRequester.getValueAt(row, 0);
        if(request.getStatus().equalsIgnoreCase("Funds Processed")){
            JOptionPane.showMessageDialog(null, "Funds are already processed!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        request.setStatus("Raise Funds");
        request.setMessage("Help organization for Funds");
        Network network = (Network) comboBoxFundRequesterName.getSelectedItem();
                for (Enterprise ent : network.getEnterpriseDirectory().getListOfEnterprises()) {
                if (ent.enterpriseType.equalsIgnoreCase(Enterprise.EnterpriseType.FundRaiser.getValue())) {
                    for(UserAccount adminUser : ent.getUserAccountDirectory().getListOfUserAccounts()) {
                        if(adminUser.getRole() instanceof AdminRole) {
                            adminUser.getWorkQueue().getListOfWorkRequests().add(request);
                            JOptionPane.showMessageDialog(this, "Registration submitted Successfully. Sent to Fund Admin for Approval!");

                        }
                    }
                }
            }
       populateNetworkTable();
    }//GEN-LAST:event_btnAssignActionPerformed

     void populateNetworkTable() {
        comboBoxFundRequesterName.removeAllItems();
        for (Network network : system.getListOfNetworks()) {
            comboBoxFundRequesterName.addItem(network);
        }
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblNetwork.getModel();
        model.setRowCount(0);
        for (Network network : system.getListOfNetworks()) {
             EnterpriseDirectory ed = network.getEnterpriseDirectory();
            for (Enterprise e : ed.getListOfEnterprises()) {
                if (e.getEnterpriseType().equalsIgnoreCase("Fund Raiser")) {
                    Object[] row = new Object[2];
                    row[0] = network.getName();
                    int funds = e.getFundsCollected();
                    if (funds >= 0) {
                        row[1] = e.getFundsCollected();
                    }
                    model.addRow(row);
                }
            }
        }
        
        DefaultTableModel model1 = new DefaultTableModel();
        model1 = (DefaultTableModel) tblFundRequester.getModel();
        model1.setRowCount(0);
        UserAccount user = system.getUserAccountDirectory().getListOfUserAccounts().get(0);
            for (WorkRequest r : user.getWorkQueue().getListOfWorkRequests()) {
                if (r.getStatus().equals("FundsNeeded")) {
                    Object[] row = new Object[4];
                    row[0] = r;
                    row[1] = r.getStatus();
                    row[2] = r.getMessage();
                    row[3] = r.getRequest().getRequestedAmount();
                    model1.addRow(row);
                }
            }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox<Object> comboBoxFundRequesterName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFundRequesterName;
    private javax.swing.JTable tblFundRequester;
    private javax.swing.JTable tblNetwork;
    // End of variables declaration//GEN-END:variables
}
